export enum ClientPacketTypeEnum {
  CREATE_BLOCK_LAND = 'CREATE_BLOCK_LAND',
  CREATE_STRUCT_BLOCK_LAND = 'CREATE_STRUCT_BLOCK_LAND',
  CREATE_DECORATION_BLOCK_LAND = 'CREATE_DECORATION_BLOCK_LAND',
  CREATE_PLANT_BLOCK_LAND = 'CREATE_PLANT_BLOCK_LAND',
  MINT_STRUCT_BLOCK_LAND = 'MINT_STRUCT_BLOCK_LAND',
  HARVEST_PLANT_BLOCK_LAND = 'HARVEST_PLANT_BLOCK_LAND',
  THEFT_PLANT_BLOCK_LAND = 'THEFT_PLANT_BLOCK_LAND',
  DELETE_STRUCT_BLOCK_LAND = 'DELETE_STRUCT_BLOCK_LAND',
  DELETE_DECORATION_BLOCK_LAND = 'DELETE_DECORATION_BLOCK_LAND',
}

export enum ServerPacketTypeEnum {}

export enum ErrorPacketTypeEnum {
  NOT_FOUND_ERROR = 'NOT_FOUND_ERROR',
  BAD_REQUEST_ERROR = 'BAD_REQUEST_ERROR',
  UNAUTHORIZED_ERROR = 'UNAUTHORIZED_ERROR',
}
